spring.application.name=pantry-pal
spring.config.import=optional:file:.env[.properties]

# TODO: use this for deployment
spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway

# This is for local dev
# spring.datasource.url=jdbc:postgresql://nozomi.proxy.rlwy.net:28669/railway

spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# Comment this for local dev
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=${PORT:8080}    
app.cors.allowed-origin-patterns=${CORS_ALLOWED_ORIGIN_PATTERNS:http://localhost:*,http://127.0.0.1:*,https://*.vercel.app}

gemini.apiKey=${GEMINI_API_KEY:}
gemini.model=${GEMINI_MODEL:gemini-2.5-flash}

usda.apiKey=${USDA_API_KEY:}

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
